Total : 0 || Sort : OK
Total : 6 || Sort : OK
Total : 6 || Sort : OK
Total : 5 || Sort : OK
Total : 3 || Sort : OK
Total : 7 || Sort : OK
Total : 4 || Sort : OK
Total : 7 || Sort : OK
Total : 8 || Sort : OK
Total : 6 || Sort : OK
Total : 9 || Sort : OK
Total : 11 || Sort : OK
Total : 5 || Sort : OK
Total : 10 || Sort : OK
Total : 10 || Sort : OK
Total : 8 || Sort : OK
Total : 8 || Sort : OK
Total : 10 || Sort : OK
Total : 8 || Sort : OK
Total : 11 || Sort : OK
Total : 11 || Sort : OK
Total : 9 || Sort : OK
Total : 9 || Sort : OK
Total : 11 || Sort : OK
